services:
  - type: web
    name: memestream
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: MODEL_NAME
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: MEME_URL
        sync: false
      - key: TAG_MEME
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: "3300"
      
crons:
  - name: heartbeat
    schedule: "*/10 * * * *"
    command: "curl -f https://meme-bot-qvdj.onrender.com/health"