services:
  - type: web
    name: memestream-agent
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/bot/bot.js
    healthCheckPath: /health
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromSecret: true
      - key: GEMINI_API_KEY
        fromSecret: true
      - key: MODEL_NAME
        fromSecret: true
      - key: MEME_URL
        fromSecret: true
      - key: TAG_MEME
        fromSecret: true
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: memestream-agent
          property: url
      - key: PORT
        fromSecret: true
      - key: NODE_ENV
        value: production